### ISSUE TITLE
error in windows os :tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: Log/train/2020-08-01 23:46:01; Invalid argument

### ISSUE THREAD

**Issue by Johnzu-2019** [2012013382/C3D-Tensorflow-slim#6]
![error1](https://user-images.githubusercontent.com/57005725/89106114-c75a8e80-d459-11ea-8f73-d57d1c388cd6.JPG)

**Comment by Johnzu-2019** [comment]
Traceback (most recent call last):
  File "E:/project/python/C3D-Tensorflow-slim-master/C3D-Tensorflow-slim-master/train.py", line 48, in <module>
    train_summary_writer = tf.compat.v1.summary.FileWriter(TRAIN_LOG_DIR, sess.graph)
  File "C:\Users\Joe\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\summary\writer\writer.py", line 367, in __init__
    filename_suffix)
  File "C:\Users\Joe\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\summary\writer\event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "C:\Users\Joe\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "C:\Users\Joe\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: Log/train/2020-08-02 00:45:32; Invalid argument

Process finished with exit code 1

**Comment by 2012013382** [comment]
Hi, John.
You need to make sure that your account has the right to mkdir the
filefold, and make sure that there is "./Log" in your file system.
Best regards!
Changsu.

Johnzu-2019 <notifications@github.com> 于2020年8月2日周日 上午12:44写道：

**Comment by sdusongzikun** [comment]
“ : ” is not allowed in windows
